version: '3.8'
services:
  jenkins:
    build:
      context: .
      dockerfile: Jenkins.Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  dind:
    build:
      context: .
      dockerfile: Docker.Dockerfile
    privileged: true

volumes:
  jenkins_data:
